//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siogas2.Resources
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesLogger
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesLogger()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siogas2.Resources.MessagesLogger", typeof(MessagesLogger).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Servicio {0} - Controlador {1}. Se produjo un error desconocido al intentar cambiar la clave del usuario {2}. Detalle: {3}.
        /// </summary>
        public static string LOGGER_CAMBIAR_CLAVE_ERROR_DESCONOCIDO
        {
            get
            {
                return ResourceManager.GetString("LOGGER_CAMBIAR_CLAVE_ERROR_DESCONOCIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error en servicio {0} del controlador {1}. Detalle: {2}.
        /// </summary>
        public static string LOGGER_ERROR_SERVICIO
        {
            get
            {
                return ResourceManager.GetString("LOGGER_ERROR_SERVICIO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo agregar un favoritos existente..
        /// </summary>
        public static string LOGGER_FAVORITO_EXISTENTE
        {
            get
            {
                return ResourceManager.GetString("LOGGER_FAVORITO_EXISTENTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Finalizando servicio {0} del controlador {1}..
        /// </summary>
        public static string LOGGER_FIN_SERVICIO
        {
            get
            {
                return ResourceManager.GetString("LOGGER_FIN_SERVICIO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Iniciando servicio {0} del controlador {1}..
        /// </summary>
        public static string LOGGER_INICIAR_SERVICIO
        {
            get
            {
                return ResourceManager.GetString("LOGGER_INICIAR_SERVICIO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Usuario {0} no pudo iniciar sesión..
        /// </summary>
        public static string LOGGER_USER_AUTH
        {
            get
            {
                return ResourceManager.GetString("LOGGER_USER_AUTH", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Servicio {0} - Controlador {1}. Se produjo un error desconocido al intentar validar las credenciales del usuario {2}. Detalle: {3}.
        /// </summary>
        public static string LOGGER_VALIDAR_CREDENCIAL_ERROR_DESCONOCIDO
        {
            get
            {
                return ResourceManager.GetString("LOGGER_VALIDAR_CREDENCIAL_ERROR_DESCONOCIDO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El usuario {0} se le ha vencido la clave. Detalle: {1}.
        /// </summary>
        public static string LOGGER_WARN_CLAVE_VENCIDA
        {
            get
            {
                return ResourceManager.GetString("LOGGER_WARN_CLAVE_VENCIDA", resourceCulture);
            }
        }
    }
}
