//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siogas2.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessagesApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesApp() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Siogas2.Resources.MessagesApp", typeof(MessagesApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña de usuario cambiada correctamente..
        /// </summary>
        public static string _200_CLAVE_CAMBIADA {
            get {
                return ResourceManager.GetString("200_CLAVE_CAMBIADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación eliminada con éxito.
        /// </summary>
        public static string _200_ELIMINACION_ASIGNACIONES {
            get {
                return ResourceManager.GetString("200_ELIMINACION_ASIGNACIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminación exitosa.
        /// </summary>
        public static string _200_ELIMINACION_REGISTROS_ERRORES_NOMINACION {
            get {
                return ResourceManager.GetString("200_ELIMINACION_REGISTROS_ERRORES_NOMINACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pantalla agregada a favoritos correctamente..
        /// </summary>
        public static string _200_FAVORITOS_ADICIONAR {
            get {
                return ResourceManager.GetString("200_FAVORITOS_ADICIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pantalla eliminada de favoritos correctamente..
        /// </summary>
        public static string _200_FAVORITOS_ELIMINAR {
            get {
                return ResourceManager.GetString("200_FAVORITOS_ELIMINAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignación exitosa.
        /// </summary>
        public static string _200_GUARDAR_ASIGNACION {
            get {
                return ResourceManager.GetString("200_GUARDAR_ASIGNACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información actualizada correctamente..
        /// </summary>
        public static string _200_INFO_ACTUALIZAR {
            get {
                return ResourceManager.GetString("200_INFO_ACTUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información guardada correctamente..
        /// </summary>
        public static string _200_INFO_ADICIONAR {
            get {
                return ResourceManager.GetString("200_INFO_ADICIONAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electronico enviado correctamente..
        /// </summary>
        public static string _200_INFO_CORREO_ENVIADO {
            get {
                return ResourceManager.GetString("200_INFO_CORREO_ENVIADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Información eliminada correctamente..
        /// </summary>
        public static string _200_INFO_ELIMINAR {
            get {
                return ResourceManager.GetString("200_INFO_ELIMINAR", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Relación de contacto con cliente se guardo correctamente..
        /// </summary>
        public static string _200_INFO_RELACION_CONTACTO {
            get {
                return ResourceManager.GetString("200_INFO_RELACION_CONTACTO", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Relación de oficina con cliente se guardo correctamente..
        /// </summary>
        public static string _200_INFO_RELACION_OFICINA {
            get {
                return ResourceManager.GetString("200_INFO_RELACION_OFICINA", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Relación de productores con la fuente de suministro se guardo correctamente..
        /// </summary>
        public static string _200_INFO_RELACION_PRODUCTOR {
            get {
                return ResourceManager.GetString("200_INFO_RELACION_PRODUCTOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Punto salida con nodo se guardó correctamente..
        /// </summary>
        public static string _200_INFO_RELACION_PUNTOSALIDA {
            get {
                return ResourceManager.GetString("200_INFO_RELACION_PUNTOSALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación de Sector con nodo se guardó correctamente..
        /// </summary>
        internal static string _200_INFO_RELACION_SECTOR {
            get {
                return ResourceManager.GetString("200_INFO_RELACION_SECTOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Relación de tipo de agente con cliente se guardo correctamente..
        /// </summary>
        public static string _200_INFO_RELACION_TIPOAGENTE {
            get {
                return ResourceManager.GetString("200_INFO_RELACION_TIPOAGENTE", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Reproceso Exitoso.
        /// </summary>
        public static string _200_REPROCESAR_CTA_008 {
            get {
                return ResourceManager.GetString("200_REPROCESAR_CTA_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reversión exitosa.
        /// </summary>
        internal static string _200_REVERTIR_ELIMINACION_REGISTRO_ERRORES_NOMINACION {
            get {
                return ResourceManager.GetString("200_REVERTIR_ELIMINACION_REGISTRO_ERRORES_NOMINACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario validado correctamente. &lt;br /&gt;{0}..
        /// </summary>
        internal static string _200_USUARIO_VALIDADO {
            get {
                return ResourceManager.GetString("200_USUARIO_VALIDADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario validado correctamente, pero su clave de ingreso se encuentra vencida..
        /// </summary>
        internal static string _200_USUARIO_VALIDADO_CON_CLAVE_VENCIDA {
            get {
                return ResourceManager.GetString("200_USUARIO_VALIDADO_CON_CLAVE_VENCIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error desconocido al intentar cambiar la clave de usuario..
        /// </summary>
        internal static string _409_CAMBIO_CLAVE_ERROR_DESCONOCIDO {
            get {
                return ResourceManager.GetString("409_CAMBIO_CLAVE_ERROR_DESCONOCIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha presentado una falla al intentar enviar el correo electronico..
        /// </summary>
        internal static string _409_ERROR_CORREO_NO_ENVIADO {
            get {
                return ResourceManager.GetString("409_ERROR_CORREO_NO_ENVIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede agregar una pantalla que ya se encuentra dentro de los favoritos..
        /// </summary>
        internal static string _409_FAVORITOS_CONFLICT {
            get {
                return ResourceManager.GetString("409_FAVORITOS_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrecta..
        /// </summary>
        internal static string _409_USUARIO_INCORRECTO {
            get {
                return ResourceManager.GetString("409_USUARIO_INCORRECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error desconocido al validar las credenciales del usuario..
        /// </summary>
        internal static string _409_VALIDAR_CREDENCIAL_ERROR_DESCONOCIDO {
            get {
                return ResourceManager.GetString("409_VALIDAR_CREDENCIAL_ERROR_DESCONOCIDO", resourceCulture);
            }
        }
    }
}
